### PR TITLE
Update to mp4parse 0.9

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! (I publish)

**Comment by nox** [comment]
You have the best timing, I was going to hit the bullet and duplicate `mp4parse` in Servo. :)

**Comment by GuillaumeGomez** [comment]
You want me to make the PR for servo?

**Comment by nox** [comment]
Nope don't worry, I was just waiting on that bump.

**Comment by GuillaumeGomez** [comment]
Well it's been published so you can do it. :)

**Pull request merged**
